name: Remote SSH
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.IP }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        
        script: |
          cd karmel_backend/
          git pull origin master 
          sudo docker-compose down
          ${{ secrets.PASS}}
          sudo docker-compose up -d
