name: Python Package

on:
    push:
      branches: [ master ]
jobs:
    build:
        uses: DominikZurawski/Karmel_Backend/.github/workflows/Reusing.yml@master
        secrets:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKERHUB_REPO_FLASK: ${{secrets.DOCKERHUB_REPO_FLASK}}
      
    push_image_to_Docker_Hub:
        runs-on: ubuntu-latest
        needs: build

        steps:  
        - uses: actions/checkout@v2
        - name: Build the stack
          run: docker-compose up -d
          
        - name: Push FLASK to docker hub
          uses: docker/build-push-action@v2
          with:
            file: flask/Dockerfile
            push: true
            tags: ${{secrets.DOCKERHUB_REPO_FLASK}}
