name: Python Package

on:
    push:
      branches: [ master ]
      
jobs:
    build:
        uses: DominikZurawski/Karmel_Backend/.github/workflows/Reusing.yml@master
        secrets:
          registry_username: ${{secrets.REGISTRY_USERNAME}}
          registry_password: ${{secrets.REGISTRY_PASSWORD}}
      
    push_image_to_Docker_Hub:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./flask
        steps:           
        - name: Push FLASK to docker hub
          uses: docker/build-push-action@v2
          with:
            file: flask/Dockerfile
            push: true
            tags: ${{secrets.DOCKERHUB_REPO_FLASK}}
