name: Python Package

on:
    push:
      branches: [ master ]
      
jobs:
    deploy:
       runs-on: ubuntu-latest
       strategy:
         fail-fast: false
         matrix:
            python-version: [3.8]
       steps:
        - uses: actions/checkout@master
        - name: Initialize Python 3.7
          uses: actions/setup-python@v4.2.0
          with:
            python-version: ${{matrix.python-version}}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r ./flask/app/requirements.txt  
        - name: Check docker installed or not
          run: docker run hello-world     
    push_image_to_Docker_Hub:
        runs-on: ubuntu-latest
        needs: deploy
        defaults:
            run:
                working-directory: ./flask
        steps:
        - name: Push FLASK to docker hub
          uses: docker/build-push-action@v2
          with:
            load: true
            file: flask/Dockerfile
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
            repository: ${{secrets.DOCKERHUB_REPO_FLASK}}
            tag_with_ref: true
            tags: ${{secrets.DOCKERHUB_REPO_FLASK}}            
        - name: Push service
          run: docker push ${{secrets.DOCKERHUB_REPO_FLASK}}  
