name: Python Package

on:
    push:
      branches: [ master ]
jobs:
    build:
        uses: DominikZurawski/Karmel_Backend/.github/workflows/Reusing.yml@master
        secrets:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKERHUB_REPO_FLASK: ${{secrets.DOCKERHUB_REPO_FLASK}}
      
    push_image_to_Docker_Hub:
        runs-on: ubuntu-latest
        needs: build
        defaults:
            run:
                working-directory: ./

        steps:  
        - uses: actions/checkout@v2
        - name: Build the stack
          run: docker-compose up -d --build
          
        - name: change tag
          run: docker tag karmel_backend_flask:latest ${{secrets.DOCKERHUB_REPO_FLASK}}      

        - name: Push FLASK to docker hub          
          run: docker-compose push

