name: Reusable workflow

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      DOCKERHUB_REPO_FLASK:
        required: true
      
jobs:
    build:
       runs-on: ubuntu-latest
       strategy:
         matrix:
            python-version: [3.8]
       steps:
        - uses: actions/checkout@master
        
        - name: Initialize Python 3.7
          uses: actions/setup-python@v4.2.0
          with:
            python-version: ${{matrix.python-version}}
            
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r ./flask/app/requirements.txt  
            
    docker:
        runs-on: ubuntu-latest
        steps:
          - name: Check docker installed or not
            run: docker run hello-world    
