name: Reusable workflow example

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true
      
jobs:
    build:
       runs-on: ubuntu-latest
       strategy:
         fail-fast: false
         matrix:
            python-version: [3.8]
       steps:
        - uses: actions/checkout@master
        
        - name: Initialize Python 3.7
          uses: actions/setup-python@v4.2.0
          with:
            python-version: ${{matrix.python-version}}
            
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r ./flask/app/requirements.txt  
            
    docker:
        runs-on: ubuntu-latest
        steps:
          - name: Check docker installed or not
            run: docker run hello-world    

          - name: Log in to Docker Hub
            uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
            with:
              images: ${{secrets.DOCKERHUB_REPO_FLASK}}
